application: events-finder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

env_variables:
    DJANGO_SETTINGS_MODULE: 'eventsfinder.settings'

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on
